name: Deploy

on:
  push:
    tags:
      - "v*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Build configuration asset
        run: bash .github/scripts/build.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        
      - name: Deploy configuration asset to SolrCloud
        run: bash .github/scripts/deploy.sh
        env:
          SOLR_USER: ${{ secrets.SOLR_USER }}
          SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
