name: Test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and start services
        run: make up
        
      - name: Install Solr documents
        run: make load-data
        
      - name: Run relevancy tests
        run: make test
